baseURL = 'http://www.opiproject.org/'
languageCode = 'en-us'
title = 'Open Programmable Infrastructure Project'
theme = "ananke"
copyright = "Copyright the Open Programmable Infrastructure Fund"

[params]
  post_content_classes = "sans-serif"
  cover_dimming_class =  "bg-transparent"
  body_classes = "avenir bg-lightest-blue"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/opiproject"

[[params.ananke_socials]]
  name = "slack"
  url = "https://join.slack.com/t/opi-project/signup"
