baseURL = 'http://www.opiproject.org/'
languageCode = 'en-us'
title = 'Open Programmable Infrastructure Project'
theme = "ananke"

[params]
  post_content_classes = "sans-serif"

[[params.ananke_socials]]
  name = "github"
  url = "https://github.com/opiproject"

[[params.ananke_socials]]
  name = "slack"
  url = "https://join.slack.com/t/opi-project/signup"
